export function normalize(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
}

const RAW_MAP: Record<string, string> = {
  'Aaron Hickey': 'Аарон Хики',
  'Abbosbek Fayzullaev': 'Аббосбек Файзуллаев',
  'Abdukodir Khusanov': 'Абдукодир Хусанов',
  'Adrien Rabiot': 'Адриен Рабьо',
  'Ahmed Fathy': 'Ахмед Фатхи',
  'Ahmed Fatouh': 'Ахмед Фатух',
  'Alessandro Circati': 'Алессандро Чиркати',
  'Alex Arce': 'Алекс Арсе',
  'Alex Freeman': 'Алекс Фримен',
  'Alexander Isak': 'Александр Исак',
  'Alexandr Sojka': 'Александр Сойка',
  'Ali Olwan': 'Али Олван',
  'Alistair Johnston': 'Алистер Джонстон',
  'Amad Diallo': 'Амад Диалло',
  'Amar Dedic': 'Амар Дедич',
  'Amir Al-Ammari': 'Амир Аль-Аммари',
  'Andy Robertson': 'Энди Робертсон',
  'Anthony Elanga': 'Энтони Эланга',
  'Antonee Robinson': 'Антони Робинсон',
  'Arthur Masuaku': 'Артур Масуаку',
  'Assim Madibo': 'Ассим Мадибо',
  'Ayase Ueda': 'Аясэ Уэда',
  'Aymen Hussein': 'Аймен Хусейн',
  'Aymeric Laporte': 'Эмерик Лапорт',
  'Bernardo Silva': 'Бернарду Силва',
  'Bradley Barcola': 'Брэдли Баркола',
  'Brahim Díaz': 'Брахим Диас',
  'Brandon Thomas-Asante': 'Брэндон Томас-Асанте',
  'Breel Embolo': 'Бреэль Эмболо',
  'Brian Brobbey': 'Брайан Броббей',
  'Brian Gutiérrez': 'Брайан Гутьеррес',
  'Bruno Guimarães': 'Бруну Гимарайнс',
  'Bukayo Saka': 'Букайо Сака',
  'Caleb Yirenkyi': 'Калеб Йиренкьи',
  'Callum McCowatt': 'Каллум Маккоуэт',
  'Cameron Burgess': 'Кэмерон Берджесс',
  'Carlens Arcus': 'Карленс Аркюс',
  'Carlos Harvey': 'Карлос Харви',
  'Casemiro': 'Каземиру',
  'Chancel Mbemba': 'Шансель Мбемба',
  'Chris Richards': 'Крис Ричардс',
  'Chris Wood': 'Крис Вуд',
  'Christian Pulisic': 'Кристиан Пулишич',
  'Cody Gakpo': 'Коди Гакпо',
  'Connor Metcalfe': 'Коннор Меткалф',
  'Crysencio Summerville': 'Крисенсио Саммервилл',
  'Cucho Hernández': 'Кучо Эрнандес',
  'Cyle Larin': 'Сайл Ларин',
  'César Blackman': 'Сесар Блэкман',
  'César Montes': 'Сесар Монтес',
  'Daichi Kamada': 'Дайти Камада',
  'Damián Bobadilla': 'Дамиан Бобадилья',
  'Dani Olmo': 'Дани Ольмо',
  'Daniel Muñoz': 'Даниэль Муньос',
  'Danley Jean Jacques': 'Дэнли Жан-Жак',
  'David Møller Wolfe': 'Давид Мёллер Вольфе',
  'Declan Rice': 'Деклан Райс',
  'Denis Zakaria': 'Денис Закария',
  'Deniz Undav': 'Дениз Ундав',
  'Denzel Dumfries': 'Дензел Дюмфрис',
  'Derek Cornelius': 'Дерек Корнелиус',
  'Diego Gómez': 'Диего Гомес',
  'Douglas Santos': 'Дуглас Сантос',
  'Edin Dzeko': 'Эдин Джеко',
  'Ehsan Hajsafi': 'Эхсан Хаджсафи',
  'Elijah Just': 'Элайджа Джаст',
  'Elliot Anderson': 'Эллиот Андерсон',
  'Emam Ashour': 'Имам Ашур',
  'Eren Elmali': 'Эрен Элмалы',
  'Erling Haaland': 'Эрлинг Холанд',
  'Ermedin Demirovic': 'Эрмедин Демирович',
  'Ermin Mahmic': 'Эрмин Махмич',
  'Felix Nmecha': 'Феликс Нмеча',
  'Felix Kalu Nmecha': 'Феликс Нмеча',
  'Findlay Curtis': 'Финдли Кёртис',
  'Finn Surman': 'Финн Сёрман',
  'Florian Wirtz': 'Флориан Вирц',
  'Folarin Balogun': 'Фоларин Балогун',
  'Franck Kessié': 'Франк Кессье',
  'Frantzdy Pierrot': 'Франтзди Пьерро',
  'Gabriel Gudmundsson': 'Габриэль Гудмундссон',
  'Gervane Kastaneer': 'Жерване Кастанер',
  'Giovanni Reyna': 'Джованни Рейна',
  'Gio Reyna': 'Джованни Рейна',
  'Granit Xhaka': 'Гранит Джака',
  'Guela Doué': 'Гела Дуэ',
  'Gustavo Puerta': 'Густаво Пуэрта',
  'Hannibal Mejbri': 'Ганнибал Мейбри',
  'Harry Kane': 'Гарри Кейн',
  'Harry Souttar': 'Гарри Саттар',
  'Hassan Al-Tambakti': 'Хасан Аль-Тамбакти',
  'Homam Ahmed': 'Хомам Ахмед',
  'Hwang In-Beom': 'Хван Ин Бом',
  'In-beom Hwang': 'Хван Ин Бом',
  'Ibrahim Mbaye': 'Ибрагим Мбайе',
  'Iliman Ndiaye': 'Илиман Ндиай',
  'Ismael Saibari': 'Исмаэль Сайбари',
  'Issa Diop': 'Исса Диоп',
  'Ivan Perisic': 'Иван Перишич',
  'Jackson Porozo': 'Джексон Поросо',
  'Jacob Italiano': 'Джейкоб Италиано',
  'Jamal Musiala': 'Джамал Мусиала',
  'Jassem Gaber': 'Джасем Габер',
  'Jean-Ricner Bellegarde': 'Жан-Рикнер Бельгард',
  'Johan Manzambi': 'Йохан Манзамби',
  'Johan Mojica': 'Йохан Мохика',
  'John McGinn': 'Джон Макгинн',
  'Jonathan David': 'Джонатан Дэвид',
  'Jordan Bos': 'Джордан Бос',
  'Jordy Alcívar': 'Джорди Алсивар',
  'Joshua Kimmich': 'Йошуа Киммих',
  'Jovo Lukic': 'Йово Лукич',
  'João Neves': 'Жоау Невеш',
  'Juan Jose Cáceres': 'Хуан Хосе Касерес',
  'Jude Bellingham': 'Джуд Беллингем',
  'Julio Enciso': 'Хулио Энсисо',
  'Julián Quiñones': 'Хулиан Киньонес',
  'Juninho Bacuna': 'Жунинью Бакуна',
  'Junya Ito': 'Дзюнья Ито',
  'Juriën Gaari': 'Юриен Гаари',
  'Jáminton Campaz': 'Хаминтон Кампас',
  'Júnior Alonso': 'Жуниор Алонсо',
  'Kai Havertz': 'Кай Хаверц',
  'Kaishu Sano': 'Кайсю Сано',
  'Keito Nakamura': 'Кейто Накамура',
  'Kenny McLean': 'Кенни Маклин',
  'Koki Ogawa': 'Коки Огава',
  'Kou Itakura': 'Ко Итакура',
  'Kylian Mbappé': 'Килиан Мбаппе',
  'Ladislav Krejcí': 'Ладислав Крейчи',
  'Lamine Yamal': 'Ламин Ямаль',
  'Leandro Bacuna': 'Леандро Бакуна',
  'Lee Gi-Hyuk': 'Ли Ги Хёк',
  'Lee Kang-In': 'Ли Кан Ин',
  'Leo Østigard': 'Лео Эстигорд',
  'Lionel Messi': 'Лионель Месси',
  'Livano Comenencia': 'Ливано Коменсия',
  'Luc de Fougerolles': 'Люк де Фужероль',
  'Lucas Bergvall': 'Лукас Бергваль',
  'Lucas Paquetá': 'Лукас Пакета',
  'Luis Díaz': 'Луис Диас',
  'Luis Romo': 'Луис Ромо',
  'Mahmoud Abunada': 'Махмуд Абунада',
  'Malik Tillman': 'Малик Тиллман',
  'Marawan Attia': 'Маруан Аттия',
  'Marcel Sabitzer': 'Марсель Забитцер',
  'Marcus Rashford': 'Маркус Рэшфорд',
  'Marko Arnautovic': 'Марко Арнаутович',
  'Martin Baturina': 'Мартин Батурина',
  'Martin Ødegaard': 'Мартин Эдегор',
  'Matheus Cunha': 'Матеус Кунья',
  'Mattias Svanberg': 'Маттиас Сванберг',
  'Matías Galarza': 'Матиас Галарса',
  'Maurício': 'Маурисио',
  'Mauricio': 'Маурисио',
  'Maxim De Cuyper': 'Максим Де Кёйпер',
  'Memphis Depay': 'Мемфис Депай',
  'Michael Olise': 'Майкл Олисе',
  'Michal Sadílek': 'Михал Садилек',
  'Micky van de Ven': 'Микки ван де Вен',
  'Miguel Almirón': 'Мигель Альмирон',
  'Mikel Oyarzabal': 'Микель Ойарсабаль',
  'Miro Muheim': 'Миро Мухайм',
  'Mohamed Hany': 'Мохамед Хани',
  'Mohamed Kanno': 'Мохаммед Канно',
  'Mohamed Manai': 'Мохамед Манаи',
  'Mohamed Salah': 'Мохамед Салах',
  'Mohammad Mohebbi': 'Мохаммад Мохеби',
  'Mohanad Lashin': 'Моханад Лашин',
  'Mostafa Zico': 'Мостафа Зико',
  'Nadiem Amiri': 'Надим Амири',
  'Nathan Ngoy': 'Натан Нгой',
  'Nathan Saliba': 'Натан Салиба',
  'Nathaniel Brown': 'Нэтаниэл Браун',
  'Nestory Irankunda': 'Нестори Иранкунда',
  'Nestor Irankunda': 'Нестори Иранкунда',
  'Nico Elvedi': 'Нико Эльведи',
  'Nico González': 'Нико Гонсалес',
  'Nico Schlotterbeck': 'Нико Шлоттербек',
  'Nikola Katic': 'Никола Катич',
  'Nkosinathi Sibisi': 'Нкосинати Сибиси',
  'Noor Al-Rawabdeh': 'Нур Аль-Равабда',
  'Nélson Semedo': 'Нелсон Семеду',
  'Oh Hyeon-Gyu': 'О Хён Гю',
  'Hyun-Gyu Oh': 'О Хён Гю',
  'Omar Rekik': 'Омар Рекик',
  'Paik Seung-Ho': 'Пэк Сын Хо',
  'Paul Okon-Engstler': 'Пол Окон-Энгстлер',
  'Pedri': 'Педри',
  'Pedro Neto': 'Педру Нету',
  'Petar Musa': 'Петар Муса',
  'Petar Sucic': 'Петар Сучич',
  'Promise David': 'Промис Дэвид',
  'Ramin Rezaeian': 'Рамин Резаян',
  'Rani Khedira': 'Рани Хедира',
  'Raúl Jiménez': 'Рауль Хименес',
  'Roberto Alvarado': 'Роберто Альварадо',
  'Rodrigo De Paul': 'Родриго Де Пауль',
  'Roger Ibañez': 'Роже Ибаньес',
  'Romano Schmid': 'Романо Шмид',
  'Romelu Lukaku': 'Ромелу Лукаку',
  'Rubén Vargas': 'Рубен Варгас',
  'Ryan Gravenberch': 'Райан Гравенберх',
  'Saeid Ezatolahi': 'Саид Эзатолахи',
  'Salem Al-Dawsari': 'Салем Аль-Давсари',
  'Sarpreet Singh': 'Сарприт Сингх',
  'Sead Kolasinac': 'Сеад Колашинац',
  'Seko Fofana': 'Секу Фофана',
  'Sidny Lopes Cabral': 'Сидни Лопеш Кабрал',
  'Sphephelo Sithole': 'Сфефело Ситоле',
  'Takefusa Kubo': 'Такефуса Кубо',
  'Tarik Muharemovic': 'Тарик Мухаремович',
  'Teboho Mokoena': 'Тебохо Мокоена',
  'Thalente Mbatha': 'Таленте Мбата',
  'Themba Zwane': 'Темба Зване',
  'Tim Payne': 'Тим Пейн',
  'Timothy Castagne': 'Тимоти Кастань',
  'Tomás Araújo': 'Томаш Араужу',
  'Trézéguet': 'Трезеге',
  'Tyler Adams': 'Тайлер Адамс',
  'Viktor Gyökeres': 'Виктор Дьёкереш',
  'Vinícius Júnior': 'Винисиус Жуниор',
  'Vinicius Junior': 'Винисиус Жуниор',
  'Virgil van Dijk': 'Вирджил ван Дейк',
  'Vladimír Coufal': 'Владимир Коуфал',
  'Wilfried Singo': 'Вильфрид Синго',
  'Xaver Schlager': 'Ксавер Шлагер',
  'Yasin Ayari': 'Ясин Аяри',
  'Yazan Al-Arab': 'Язан Аль-Араб',
  'Yoane Wissa': 'Йоан Висса',
  'Yunus Akgün': 'Юнус Акгюн',
  'Zaid Tahseen': 'Заид Тахсин',
  'Érik Lira': 'Эрик Лира',
  'Maximiliano Araújo': 'Максимилиано Араухо',
  'Boualem Khoukhi': 'Буалем Хухи',
  'Abdulelah Al Amri': 'Абдулелах Аль-Амри',
}

const PLAYER_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_MAP).map(([name, ru]) => [normalize(name), ru])
)

export function playerRu(name: string | null | undefined): string {
  if (!name) return ''
  const trimmed = name.trim()
  return PLAYER_MAP[normalize(trimmed)] ?? trimmed
}
